import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        primary: {
          DEFAULT: "var(--primary)",
          foreground: "var(--primary-foreground)",
          50: "var(--primary-50)",
          100: "var(--primary-100)",
          200: "var(--primary-200)",
          300: "var(--primary-300)",
          400: "var(--primary-400)",
          500: "var(--primary-500)",
          600: "var(--primary-600)",
          700: "var(--primary-700)",
          800: "var(--primary-800)",
          900: "var(--primary-900)",
          "50-text": "var(--primary-50-text)",
          "100-text": "var(--primary-100-text)",
          "200-text": "var(--primary-200-text)",
          "300-text": "var(--primary-300-text)",
          "400-text": "var(--primary-400-text)",
          "500-text": "var(--primary-500-text)",
          "600-text": "var(--primary-600-text)",
          "700-text": "var(--primary-700-text)",
          "800-text": "var(--primary-800-text)",
          "900-text": "var(--primary-900-text)",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          foreground: "var(--secondary-foreground)",
          50: "var(--secondary-50)",
          100: "var(--secondary-100)",
          200: "var(--secondary-200)",
          300: "var(--secondary-300)",
          400: "var(--secondary-400)",
          500: "var(--secondary-500)",
          600: "var(--secondary-600)",
          700: "var(--secondary-700)",
          800: "var(--secondary-800)",
          900: "var(--secondary-900)",
          "50-text": "var(--secondary-50-text)",
          "100-text": "var(--secondary-100-text)",
          "200-text": "var(--secondary-200-text)",
          "300-text": "var(--secondary-300-text)",
          "400-text": "var(--secondary-400-text)",
          "500-text": "var(--secondary-500-text)",
          "600-text": "var(--secondary-600-text)",
          "700-text": "var(--secondary-700-text)",
          "800-text": "var(--secondary-800-text)",
          "900-text": "var(--secondary-900-text)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          foreground: "var(--accent-foreground)",
          50: "var(--accent-50)",
          100: "var(--accent-100)",
          200: "var(--accent-200)",
          300: "var(--accent-300)",
          400: "var(--accent-400)",
          500: "var(--accent-500)",
          600: "var(--accent-600)",
          700: "var(--accent-700)",
          800: "var(--accent-800)",
          900: "var(--accent-900)",
          "50-text": "var(--accent-50-text)",
          "100-text": "var(--accent-100-text)",
          "200-text": "var(--accent-200-text)",
          "300-text": "var(--accent-300-text)",
          "400-text": "var(--accent-400-text)",
          "500-text": "var(--accent-500-text)",
          "600-text": "var(--accent-600-text)",
          "700-text": "var(--accent-700-text)",
          "800-text": "var(--accent-800-text)",
          "900-text": "var(--accent-900-text)",
        },
        muted: {
          DEFAULT: "var(--muted)",
          foreground: "var(--muted-foreground)",
        },
        destructive: {
          DEFAULT: "var(--destructive)",
          foreground: "var(--destructive-foreground)",
        },
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [],
};

export default config;
